apiVersion: v1
kind: Pod
metadata:
  name: restart-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: sleep-container
      image: alpine:latest
      command: ["sh", "-c", "sleep 604800"]